# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the TRAP affinity for one or more sequences (one score per sequence)
#'
#' @param pwm The position weight matrix
#' @param motiflength The length of the PWM
#' @param sequence a list of one or more genomic sequences
#' @param seqlength the lengths of the sequences
#' @param Rmax rmax
#' @param lambda lambda
#' @param bothstrands should the affinity be calcuated on both strands (DNA) or just one (RNA)
#' @return a numeric vector of the scores for each sequence
#' @export
R_affinity_sum_multi <- function(pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands) {
    .Call('_tRap_R_affinity_sum_multi', PACKAGE = 'tRap', pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands)
}

#' Calculate the TRAP affinity for each position along one or more sequences
#'
#' @inheritParams R_affinity_sum_multi
#' @return a list where each element is a numeric vector containing the
#' scores along the length of a single sequence.
#' @export
R_affinity_multi <- function(pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands) {
    .Call('_tRap_R_affinity_multi', PACKAGE = 'tRap', pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands)
}

