# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
R_affinity_sum_multi <- function(pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands) {
    .Call('tRap_R_affinity_sum_multi', PACKAGE = 'tRap', pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands)
}

#' @export
R_affinity_multi <- function(pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands) {
    .Call('tRap_R_affinity_multi', PACKAGE = 'tRap', pwm, motiflength, sequence, seqlength, Rmax, lambda, bothstrands)
}

